In [87]:
import torch
import torch.nn as nn
import numpy as np

In [88]:
X = np.arange(30, dtype="float32").reshape(10, -1)
Xt = torch.tensor(X)

In [89]:
y = np.arange(10, dtype="float32").reshape(-1, 1)
yt = torch.tensor(y)

In [263]:
N = 3

In [264]:
net = nn.Sequential(nn.Linear(3, 1))
net.zero_grad()

In [265]:
criterion = nn.MSELoss()

In [268]:
yp = net(Xt[:N])

In [269]:
W = net[0].weight.data.numpy()
b = net[0].bias.data.numpy()

In [270]:
yn = np.dot(X[:N], W.T) + b

In [271]:
loss = criterion(yt[:N], yp)

In [272]:
loss

tensor(21.6302, grad_fn=<MeanBackward0>)

In [273]:
print(W, b)

[[0.45566845 0.4854604  0.39938873]] [-0.36324745]


In [274]:
print(yp, yn)

tensor([[0.9210],
        [4.9425],
        [8.9641]], grad_fn=<AddmmBackward>) [[0.9209904]
 [4.9425435]
 [8.964095 ]]


In [275]:
loss.backward()

In [276]:
print(net[0].weight.grad, net[0].bias.grad)

tensor([[35.7415, 43.6266, 51.5116]]) tensor([7.8851])


In [277]:
X[0:N]

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [279]:
dloss = (-2/len(yn))*np.sum((y[0:N] - yn))
dloss

7.8850860595703125

In [280]:
cc = dloss * X[0:N]

In [281]:
cc

array([[ 0.      ,  7.885086, 15.770172],
       [23.655258, 31.540344, 39.42543 ],
       [47.310516, 55.195602, 63.08069 ]], dtype=float32)

In [282]:
np.mean(cc, axis=0)

array([23.655258, 31.540344, 39.42543 ], dtype=float32)

In [284]:
net[0].weight.grad.numpy() / np.mean(cc, axis=0)

array([[1.5109314, 1.3831985, 1.3065588]], dtype=float32)